### ISSUE TITLE
The --long option is not reporting file sizes accurately

### ISSUE THREAD

**Issue by rbeyer** [athityakumar/colorls#617] opened 2024-06-05 00:31 UTC
### Description

The reported file size in `colorls --long` is different (maybe truncated) than what `ls -lh` reports, which could be misleading.

colorls version 1.4.6
- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue : Bug in existing feature

For example:
```
$> ls -l CUMINDEX.TAB
-rw-r--r--  1 rbeyer  staff  3163642328 Aug  8  2023 CUMINDEX.TAB

$> ls -lh CUMINDEX.TAB
-rw-r--r--  1 rbeyer  staff   2.9G Aug  8  2023 CUMINDEX.TAB

$> colorls --long CUMINDEX.TAB
   rw-r--r--   1   rbeyer   staff      2 GiB   Tue Aug  8 10:51:25 2023    CUMINDEX.TAB
```

*colorls* is reporting that this file is only 2 GiB, while *ls* is reporting 2.9 GB, which is almost a gigabyte different!

**Comment by avdv** [comment] 2024-06-30 14:14
Duplicate of #600

**Closed by avdv** 2024-06-30 14:14 UTC
