### ISSUE TITLE
The  sequence of display iterms

### ISSUE THREAD

**Issue by yuanzhe-liu** [athityakumar/colorls#225] opened 2018-10-18 06:48 UTC
### Description

Hello,
Thank u for write this amazing awesome utility. But i found a little insufficient, the sequence of display items is not as same as the origin `ls` command do.Here i have two pictures:

![from ls](https://user-images.githubusercontent.com/44017689/47069022-7a73dc80-d220-11e8-949c-dea71a91c05c.png)
![from colorls](https://user-images.githubusercontent.com/44017689/47069028-7fd12700-d220-11e8-8272-a00b9066d017.png)

As u can see, the origin ls display vertical first, but colorls display horizontal.Since i am used to the 
vertical display, colorls make me uncomfortable if there are many iterms to show.

So could u add this feature? I am sure this will make colorls more powerful.

The
- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment] 2018-10-18 07:42
Duplicate of #189

**Closed by avdv** 2018-10-18 07:42 UTC
Labels: duplicate
