### ISSUE TITLE
colorls with more than zero file gives output with extra newlines

### ISSUE THREAD

**Issue by craigemery** [athityakumar/colorls#427] opened 2020-12-10 17:36 UTC
### Description

If I run
$ colorls
i.e. with no arguments, all the files are listed with no blank lines.

If I run
$ colorls *.ext
Then the files are all listed with an extra newline between each one.
This feels wrong.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

I see this on macOS and Windows WSL.
colorls --version is 1.4.2

**Comment by craigemery** [comment] 2020-12-10 17:38
In fact colorls always shows a blank line, but when calling
$ colours
i.e. by itself, there's only one blank line & it's immediately before my prompt appears.
So it's just really noticeable when the blank line appears after every individually specified file.

**Comment by avdv** [comment] 2020-12-22 21:35
Hi, thanks for bringing this up again!

This is basically a known bug which is not easy to fix since the current code structure revolves around the concept of processing each command line argument in separation (especially in regard to the `--report` option which prints a report after each argument).

What should be done instead is group all arguments into files and directories. Print all file arguments as one group and then print every directory as subsequent groups.

**Comment by avdv** [comment] 2020-12-23 21:30
Duplicate of #233

**Closed by avdv** 2020-12-23 21:30 UTC
Labels: duplicate
