### ISSUE TITLE
Can't re-install colorls after updating to macOS Big Sur

### ISSUE THREAD

**Issue by odebroqueville** [athityakumar/colorls#418] opened 2020-11-21 17:35 UTC
### Description

Colorls was broken after updating to macOS Big Sur, so I tried uninstalling and re-installing with sudo gem (un)install colorls, but I'm getting an error message:

<img width="1172" alt="Screenshot 2020-11-21 at 18 14 48" src="https://user-images.githubusercontent.com/4818315/99883365-405b3d00-2c27-11eb-9576-8e9e2509b734.png">

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [x] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

Here are the contents of the mkmf.log file:

```
"xcrun clang -o conftest -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin20 -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/backward -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -g -Os -pipe -DHAVE_GCC_ATOMIC_BUILTINS -DUSE_FFI_CLOSURE_ALLOC conftest.c  -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib -L. -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.Internal.sdk/usr/local/lib     -lruby.2.6   "
In file included from conftest.c:1:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby.h:33:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
         ^~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:24:10: note: did not find header 'config.h' in framework 'ruby' (loaded from '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks')
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

```

and this is the result of gem env: (makes me wonder if gems are getting installed in several places?!)

```
❯ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.3
  - RUBY VERSION: 2.6.3 (2019-04-16 patchlevel 62) [universal.x86_64-darwin20]
  - INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.6.0
  - USER INSTALLATION DIRECTORY: /Users/odebroqueville/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /Users/odebroqueville/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-20
  - GEM PATHS:
     - /Library/Ruby/Gems/2.6.0
     - /Users/odebroqueville/.gem/ruby/2.6.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Applications/Julia-1.5.app/Contents/Resources/julia/bin
     - /Users/odebroqueville/.deno/bin
     - /Users/odebroqueville/opt/anaconda3/bin
     - /Users/odebroqueville/opt/anaconda3/condabin
     - /Users/odebroqueville/.nvm/versions/node/v15.0.0/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/Apple/usr/bin
     - /Users/odebroqueville/development/flutter/bin
```

**Comment by avdv** [comment] 2020-11-21 19:34
Duplicate of #414. You have to (re)install xcode first. See also https://github.com/athityakumar/colorls/issues/386#issuecomment-727265525

**Closed by avdv** 2020-11-21 19:34 UTC

**Comment by avdv** [comment] 2020-11-21 19:39
> and this is the result of gem env: (makes me wonder if gems are getting installed in several places?!)

Yes, there are several places for gems. You can install gems to your user gem folder with `gem install --user-install colorls`, so you don't have to use `sudo`.

**Comment by odebroqueville** [comment] 2020-11-21 21:49
Problem solved! Thank you!
