### ISSUE TITLE
 incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by iNoSec2** [athityakumar/colorls#508] opened 2022-03-21 05:59 UTC
[### Description
I have the same issue than this closed issue https://github.com/athityakumar/colorls/issues/242#issue-387638261 it is on the same exact directory than the latest user, `Téléchargements`
![image](https://user-images.githubusercontent.com/51358868/159211816-8c95fa08-7d88-4359-9c7a-570aff74e7eb.png)

The tricks `export LC_CTYPE=blabla` didnt work in my case

- Relevant Issues : [Same issue than this one](https://github.com/athityakumar/colorls/issues/242#issue-387638261)
- Type of issue :
  - [ ] Installation
  - [x] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment] 2022-03-21 08:00
Duplicate of https://github.com/athityakumar/colorls/issues/449

**Closed by avdv** 2022-03-21 08:00 UTC

**Comment by iNoSec2** [comment] 2022-03-21 11:05
> Duplicate of #449

Why this is still in pré release since 2021?
Thank you

**Comment by avdv** [comment] 2022-03-21 12:27
> Why this is still in pré release since 2021?

We had to switch from Travis.org CI to something else because the service had been sunset. Github Actions was the easiest solution, but I have no permissions to change settings here (it's not my project) and because of this I cannot push out releases to RubyGems any longer. See #509

**Comment by iNoSec2** [comment] 2022-03-21 14:16
Ok, thankbyou again for your help
