### ISSUE TITLE
Blank lines in -la mode

### ISSUE THREAD

**Issue by Yamp** [athityakumar/colorls#284] opened 2019-05-11 00:08 UTC
### Description

Thanks for opening this issue. Add a brief description of what this issue is, and how to recreate it. Do tag the relevant issue(s) and PR(s) below. If required, add some screenshot(s) to showcase the issue.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ x ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

![image](https://user-images.githubusercontent.com/5207009/57562291-09ea0400-739a-11e9-81a0-e3144579a7ef.png)

![image](https://user-images.githubusercontent.com/5207009/57562298-18382000-739a-11e9-9027-b99e49d42dff.png)

**Comment by avdv** [comment] 2019-05-11 15:42
That's a known issue and has nothing to do with `-la`. Duplicate of #233

**Closed by avdv** 2019-05-11 15:42 UTC
