### ISSUE TITLE
root missing in view, causes alignment issues

### ISSUE THREAD

**Issue by pguetschow** [athityakumar/colorls#202] opened 2018-07-18 06:04 UTC
### Description

When displaying the list with`ll` the owner entry is missing, when the owner is root. As a result, the whole row has a different alignment. 
![](https://i.imgur.com/CtAT0qQ.png) 

Terminal: Hyper w/ Oh My Zsh
OS: macOS HighSierra 10.13.5

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment] 2018-07-18 07:04
duplicate of #187, fixed by PR #188 but not yet released...

**Comment by pguetschow** [comment] 2018-07-18 08:22
@avdv Whoops, only read through the open issues

**Closed** 2020-10-24 11:43 UTC
Labels: Language:Ruby, bug, duplicate
