### ISSUE TITLE
No colors on MSYS2

### ISSUE THREAD

**Issue by chwba** [athityakumar/colorls#223] opened 2018-10-06 11:00 UTC
### Description

When using this with MSYS2 on Windows 10 Pro it now works (thanks to fixing https://github.com/athityakumar/colorls/issues/220) but unfortunately still without colors. I already tried to apply a custom color set as per https://github.com/athityakumar/colorls/issues/165 but it didn't help.
![screenshot_6](https://user-images.githubusercontent.com/22568014/46570649-a1502a00-c967-11e8-8e57-ac8f4a4f0648.png)

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment] 2018-10-17 11:48
Hi @g-uru,

this is a hard one, since I am not using Windows in any way. So, just some questions:

* What's the value of your `TERM` variable?
* Does running `ruby -r rainbow -e 'puts Rainbow("This is red").red'` result in colored text?

**Comment by g-uru** [comment] 2018-10-17 18:12
![screenshot_1](https://user-images.githubusercontent.com/22568014/47107187-f255fd00-d248-11e8-873d-0a3529e68d39.png)

**Comment by avdv** [comment] 2018-10-18 07:50
Probably some sort of bug in conemu? Which version of Ruby / ConEmu are you using? Try to upgrade to the latest stable releases.

What does `ruby -e 'puts STDOUT.tty?' -e 'puts STDERR.tty?'` yield?

**Comment by chwba** [comment] 2018-10-18 23:51
![screenshot_1](https://user-images.githubusercontent.com/22568014/47190406-7c818c80-d341-11e8-9649-19ee6575cd3e.png)

**Comment by avdv** [comment] 2018-10-19 09:05
Maybe you can try the official ruby version from msys2 repositories which is at 2.4.x currently? AFAICS, the recommended ruby version from rubyinstaller.org also is 2.4.X.

Nevertheless, this is clearly not a bug in colorls. Would you consider reporting a bug with conemu instead? I am closing this issue here.

However, you should be able to work around adding `export CLICOLOR_FORCE=1` to your `.zshenv` file.

**Closed by avdv** 2018-10-19 09:05 UTC

**Comment by chwba** [comment] 2018-10-19 10:08
genius, that works 🥇

**Comment by avdv** [comment] 2018-10-19 22:20
Hey @chwba, FYI I have just added a new option for controlling output colorization onto the master branch. (see #227) You could remove the environment variable hack and simply add the option to an alias instead: 

`alias ls='colorls --color'`
