### ISSUE TITLE
Speed issues with Mac OS

### ISSUE THREAD

**Issue by benjamin-rood** [athityakumar/colorls#182] opened 2018-02-03 06:48 UTC
### Description

```
brpro ➜  .dotfiles git:(master) ✗ colorls -a
      ./                         ../                         .git/
      .gitignore                 .gitmodules                 .vadabox-aliases-funcs
      antigen/                   antigen.config              antigen.zsh
      atom/                      config-brpro/               config-linux/
      git/                       github.com/                 hostsfile
      iTerm2-Color-Schemes/      my-oh-my-zsh/               oh-my-zsh-config/
      profile                    s.asc                       sh-scripts/
      spacemacs.d/               vadabox-aliases-funcs       vscode/
      zshrc-mac
```

C.f.:
```
brpro ➜  .dotfiles git:(master) ✗ colorls -a --gs
     ✓    ./                   ^CTraceback (most recent call last):
	38: from /usr/local/bin/colorls:23:in `<main>'
	37: from /usr/local/bin/colorls:23:in `load'
	36: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/exe/colorls:5:in `<top (required)>'
	35: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/flags.rb:41:in `process'
	34: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/flags.rb:41:in `each_with_index'
	33: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/flags.rb:41:in `each'
	32: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/flags.rb:46:in `block in process'
	31: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:38:in `ls'
	30: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:38:in `each'
	29: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:38:in `block in ls'
	28: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:296:in `ls_line'
	27: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:296:in `each_with_index'
	26: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:296:in `each'
	25: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:299:in `block in ls_line'
	24: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:289:in `fetch_string'
	23: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:228:in `git_info'
	22: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:254:in `git_dir_info'
	21: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:242:in `deep_entries'
	20: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:242:in `map'
	19: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:244:in `block in deep_entries'
	18: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:242:in `deep_entries'
	17: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:242:in `map'
	16: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:244:in `block in deep_entries'
	15: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:242:in `deep_entries'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:242:in `map'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:244:in `block in deep_entries'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:242:in `deep_entries'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:242:in `map'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:244:in `block in deep_entries'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:242:in `deep_entries'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:242:in `map'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:244:in `block in deep_entries'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:242:in `deep_entries'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:242:in `map'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:244:in `block in deep_entries'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:242:in `deep_entries'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:242:in `map'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:243:in `block in deep_entries'
/usr/local/lib/ruby/gems/2.5.0/gems/colorls-1.1.0/lib/colorls/core.rb:243:in `exist?': Interrupt
```

Output always stalls after listing the `./` entry. One gives up, and kills the process with <kbd>Ctrl</kbd>+<kbd>C</kbd>.

Now, it's important to note that eventually it will return:
```
brpro ➜  .dotfiles git:(master) ✗ time colorls -a --gs
     ✓    ./                        ✓    ../                        ✓    .git/
     ✓    .gitignore                ✓    .gitmodules                ✓    .vadabox-aliases-funcs
     ✓    antigen/                  ✓    antigen.config             ✓    antigen.zsh
     ✓    atom/                     ✓    config-brpro/              ✓    config-linux/
     ✓    git/                      ✓    github.com/                M    hostsfile
     ✓    iTerm2-Color-Schemes/     ✓    my-oh-my-zsh/              ✓    oh-my-zsh-config/
     M    profile                   ✓    s.asc                      ?    sh-scripts/
     ✓    spacemacs.d/              ✓    vadabox-aliases-funcs      ✓    vscode/
     ✓    zshrc-mac
colorls -a --gs  10.27s user 30.83s system 89% cpu 45.807 total
```

45.8 SECONDS!!! 89% cpu utilisation!

Now, let's try it with my default command set, which I normally alias to `lcl`:
```
brpro ➜  .dotfiles git:(master) ✗ time colorls -la --sd --gs
  rwxr-xr-x  br  staff  850 B    Sat Feb  3 19:05:25 2018   ✓    ./
  rwxr-xr-x  br  staff    2 KiB  Sat Feb  3 19:27:45 2018   ✓    ../
  rwxr-xr-x  br  staff  510 B    Sat Feb  3 19:27:46 2018   ✓    .git/
  rwxr-xr-x  br  staff  714 B    Wed Jan 17 20:50:32 2018   ✓    antigen/
  rwxr-xr-x  br  staff  102 B    Fri Jan 12 23:54:00 2018   ✓    atom/
  rwxr-xr-x  br  staff  510 B    Fri Jan 19 18:04:01 2018   ✓    config-brpro/
  rwxr-xr-x  br  staff    1 KiB  Sat Jan 27 19:36:25 2018   ✓    config-linux/
  rwxr-xr-x  br  staff  136 B    Sat Jan 20 00:08:27 2018   ✓    git/
  rwxr-xr-x  br  staff  102 B    Fri Jan 12 23:54:08 2018   ✓    github.com/
  rwxr-xr-x  br  staff  612 B    Fri Jan 19 23:48:59 2018   ✓    iTerm2-Color-Schemes/
  rwxr-xr-x  br  staff  544 B    Sat Jan 27 19:31:28 2018   ✓    my-oh-my-zsh/
  rwxr-xr-x  br  staff  136 B    Thu Feb  1 14:01:29 2018   ✓    oh-my-zsh-config/
  rwxr-xr-x  br  staff  102 B    Wed Jan 31 10:27:16 2018   ?    sh-scripts/
  rwxr-xr-x  br  staff  102 B    Fri Jan 12 23:54:08 2018   ✓    spacemacs.d/
  rwxr-xr-x  br  staff  136 B    Fri Jan 12 23:54:08 2018   ✓    vscode/
  rw-r--r--  br  staff  315 B    Sat Jan 27 19:36:25 2018   ✓    .gitignore
  rw-r--r--  br  staff  179 B    Fri Jan 12 23:54:00 2018   ✓    .gitmodules
  rw-r--r--  br  staff   10 KiB  Fri Jan 12 23:54:00 2018   ✓    .vadabox-aliases-funcs
  rw-r--r--  br  staff   42 B    Fri Jan 12 23:54:00 2018   ✓    antigen.config
  rw-r--r--  br  staff   57 KiB  Fri Jan 12 23:54:00 2018   ✓    antigen.zsh
  rw-r--r--  br  staff  498 B    Mon Jan 29 10:45:12 2018   M    hostsfile
  rw-r--r--  br  staff    4 KiB  Sat Feb  3 19:05:25 2018   M    profile
  rw-r--r--  br  staff  630 B    Fri Jan 12 23:54:08 2018   ✓    s.asc
  rw-r--r--  br  staff   10 KiB  Fri Jan 12 23:54:08 2018   ✓    vadabox-aliases-funcs
  rw-r--r--  br  staff    3 KiB  Fri Jan 12 23:54:08 2018   ✓    zshrc-mac
colorls -la --sd --gs  10.35s user 32.29s system 85% cpu 50.009 total
```

 😵

I just want to point out that even `-l --gs` isn't as responsive as it should be:
```
brpro ➜  .dotfiles git:(master) ✗ time colorls -l --gs
  rwxr-xr-x  br  staff  714 B    Wed Jan 17 20:50:32 2018   ✓    antigen/
  rw-r--r--  br  staff   42 B    Fri Jan 12 23:54:00 2018   ✓    antigen.config
  rw-r--r--  br  staff   57 KiB  Fri Jan 12 23:54:00 2018   ✓    antigen.zsh
  rwxr-xr-x  br  staff  102 B    Fri Jan 12 23:54:00 2018   ✓    atom/
  rwxr-xr-x  br  staff  510 B    Fri Jan 19 18:04:01 2018   ✓    config-brpro/
  rwxr-xr-x  br  staff    1 KiB  Sat Jan 27 19:36:25 2018   ✓    config-linux/
  rwxr-xr-x  br  staff  136 B    Sat Jan 20 00:08:27 2018   ✓    git/
  rwxr-xr-x  br  staff  102 B    Fri Jan 12 23:54:08 2018   ✓    github.com/
  rw-r--r--  br  staff  498 B    Mon Jan 29 10:45:12 2018   M    hostsfile
  rwxr-xr-x  br  staff  612 B    Fri Jan 19 23:48:59 2018   ✓    iTerm2-Color-Schemes/
  rwxr-xr-x  br  staff  544 B    Sat Jan 27 19:31:28 2018   ✓    my-oh-my-zsh/
  rwxr-xr-x  br  staff  136 B    Thu Feb  1 14:01:29 2018   ✓    oh-my-zsh-config/
  rw-r--r--  br  staff    4 KiB  Sat Feb  3 19:05:25 2018   M    profile
  rw-r--r--  br  staff  630 B    Fri Jan 12 23:54:08 2018   ✓    s.asc
  rwxr-xr-x  br  staff  102 B    Wed Jan 31 10:27:16 2018   ?    sh-scripts/
  rwxr-xr-x  br  staff  102 B    Fri Jan 12 23:54:08 2018   ✓    spacemacs.d/
  rw-r--r--  br  staff   10 KiB  Fri Jan 12 23:54:08 2018   ✓    vadabox-aliases-funcs
  rwxr-xr-x  br  staff  136 B    Fri Jan 12 23:54:08 2018   ✓    vscode/
  rw-r--r--  br  staff    3 KiB  Fri Jan 12 23:54:08 2018   ✓    zshrc-mac
colorls -l --gs  0.37s user 0.37s system 100% cpu 0.737 total
```
C.f.:
```
brpro ➜  .dotfiles git:(master) ✗ time colorls -l
  rwxr-xr-x  br  staff  714 B    Wed Jan 17 20:50:32 2018    antigen/
  rw-r--r--  br  staff   42 B    Fri Jan 12 23:54:00 2018    antigen.config
  rw-r--r--  br  staff   57 KiB  Fri Jan 12 23:54:00 2018    antigen.zsh
  rwxr-xr-x  br  staff  102 B    Fri Jan 12 23:54:00 2018    atom/
  rwxr-xr-x  br  staff  510 B    Fri Jan 19 18:04:01 2018    config-brpro/
  rwxr-xr-x  br  staff    1 KiB  Sat Jan 27 19:36:25 2018    config-linux/
  rwxr-xr-x  br  staff  136 B    Sat Jan 20 00:08:27 2018    git/
  rwxr-xr-x  br  staff  102 B    Fri Jan 12 23:54:08 2018    github.com/
  rw-r--r--  br  staff  498 B    Mon Jan 29 10:45:12 2018    hostsfile
  rwxr-xr-x  br  staff  612 B    Fri Jan 19 23:48:59 2018    iTerm2-Color-Schemes/
  rwxr-xr-x  br  staff  544 B    Sat Jan 27 19:31:28 2018    my-oh-my-zsh/
  rwxr-xr-x  br  staff  136 B    Thu Feb  1 14:01:29 2018    oh-my-zsh-config/
  rw-r--r--  br  staff    4 KiB  Sat Feb  3 19:05:25 2018    profile
  rw-r--r--  br  staff  630 B    Fri Jan 12 23:54:08 2018    s.asc
  rwxr-xr-x  br  staff  102 B    Wed Jan 31 10:27:16 2018    sh-scripts/
  rwxr-xr-x  br  staff  102 B    Fri Jan 12 23:54:08 2018    spacemacs.d/
  rw-r--r--  br  staff   10 KiB  Fri Jan 12 23:54:08 2018    vadabox-aliases-funcs
  rwxr-xr-x  br  staff  136 B    Fri Jan 12 23:54:08 2018    vscode/
  rw-r--r--  br  staff    3 KiB  Fri Jan 12 23:54:08 2018    zshrc-mac
colorls -l  0.16s user 0.03s system 96% cpu 0.197 total
```

Note that I have no such problem on Linux, it's working fine:

<img width="657" alt="screen shot 2018-02-03 at 7 45 07 pm" src="https://user-images.githubusercontent.com/10102132/35763887-f0ac305c-091a-11e8-9cc2-16d2bf1d57f8.png">

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by athityakumar** [comment] 2018-02-03 06:52
@benjamin-rood : It's surprising that this difference is coming out due to Mac / Linux. Hmm. What're the Ruby versions in both the platforms? Maybe a slower Ruby version is Mac is resulting in this.

**Comment by benjamin-rood** [comment] 2018-02-03 06:54
macOS Sierra:
`ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]`  <-- newer

Ubuntu 16.04.3 LTS:
`ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]`

**Comment by athityakumar** [comment] 2018-02-03 16:52
Oh, that's weird. 😕

**Comment by avdv** [comment] 2018-02-03 20:38
Hi.

I could reproduce the problem on my Linux box (not as significant as what @benjamin-rood reported, but still).

The problem is that the `-a` switch also processes the parent directory (`..`), which means that the deep_entries method will completely traverse the parent directory (and each other directory of the current folder).

Try to run `time find .. -L > /dev/null` on both systems to get an idea about how much time that takes.

Why do you use `-a` instead of `-A`?

**Comment by avdv** [comment] 2018-02-04 22:38
Hey, you can try the PR #183 which should fix this by changing how the git status is determined. Also fixes a bug where it reported the wrong status for a directory. I am in a hurry right now, stay tuned.

**Comment by avdv** [comment] 2018-04-10 08:09
Hey @benjamin-rood, please try again with version 1.1.1.

**Comment by avdv** [comment] 2018-09-11 19:26
This should be fixed, re-open if there's still a problem.

**Closed by avdv** 2018-09-11 19:26 UTC
Labels: bug, help wanted, question
